version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env